import { login } from "./firebase";
import { insertBook } from "./scripts/insertBook";

// Old Testament
import { genesisBookContent } from "./data/oldTestament/genesis";
import { exodusStoryDivision } from "./data/oldTestament/Exodus";
import { leviticusStoryDivision } from "./data/oldTestament/leviticus";
import { numbersStoryDivision } from "./data/oldTestament/numbers";
import { deuteronomyStoryDivision } from "./data/oldTestament/deuteronomy";
import { joshuaStoryDivision } from "./data/oldTestament/joshua";
import { judgesStoryDivision } from "./data/oldTestament/judges";
import { ruthStoryDivision } from "./data/oldTestament/ruth";
import { firstSamuelStoryDivision } from "./data/oldTestament/1_samuel";
import { secondSamuelStoryDivision } from "./data/oldTestament/2_samuel";
import { firstKingsStoryDivision } from "./data/oldTestament/1_kings";
import { secondKingsStoryDivision } from "./data/oldTestament/2_kings";
import { firstChroniclesStoryDivision } from "./data/oldTestament/1_chronicles";
import { secondChroniclesStoryDivision } from "./data/oldTestament/2_chronicles";
import { ezraStoryDivision } from "./data/oldTestament/ezra";
import { nehemiahStoryDivision } from "./data/oldTestament/nehemiah";
import { estherStoryDivision } from "./data/oldTestament/esther";
import { jobStoryDivision } from "./data/oldTestament/job";
import { psalmsBookContent } from "./data/oldTestament/psalms";
import { proverbsStoryDivision } from "./data/oldTestament/proverbs";
import { ecclesiastesStoryDivision } from "./data/oldTestament/ecclesiastes";
import { songOfSongsStoryDivision } from "./data/oldTestament/song_of_songs";
import { isaiahStoryDivision } from "./data/oldTestament/isaiah";
import { jeremiahStoryDivision } from "./data/oldTestament/jeremiah";
import { lamentationsStoryDivision } from "./data/oldTestament/lamentations";
import { ezekielStoryDivision } from "./data/oldTestament/ezekiel";
import { danielStoryDivision } from "./data/oldTestament/daniel";
import { hoseaStoryDivision } from "./data/oldTestament/hosea";
import { joelStoryDivision } from "./data/oldTestament/joel";
import { amosStoryDivision } from "./data/oldTestament/amos";
import { obadiahStoryDivision } from "./data/oldTestament/obadiah";
import { jonahStoryDivision } from "./data/oldTestament/jonah";
import { micahStoryDivision } from "./data/oldTestament/micah";
import { nahumStoryDivision } from "./data/oldTestament/nahum";
import { habakkukStoryDivision } from "./data/oldTestament/habakkuk";
import { zephaniahStoryDivision } from "./data/oldTestament/zephaniah";
import { haggaiStoryDivision } from "./data/oldTestament/haggai";
import { zechariahStoryDivision } from "./data/oldTestament/zechariah";
import { malachiStoryDivision } from "./data/oldTestament/malachi";

// New Testament
import { matthewBookContent } from "./data/newTestament/matthew";
import { markStoryDivision } from "./data/newTestament/mark";
import { lukeStoryDivision } from "./data/newTestament/luke";
import { johnStoryDivision } from "./data/newTestament/jhon";
import { actsStoryDivision } from "./data/newTestament/acts";
import { romansStoryDivision } from "./data/newTestament/romans";
import { firstCorinthiansStoryDivision } from "./data/newTestament/1_corinthians";
import { secondCorinthiansStoryDivision } from "./data/newTestament/2_corinthians";
import { galatiansStoryDivision } from "./data/newTestament/galatians";
import { ephesiansStoryDivision } from "./data/newTestament/ephesians";
import { philippiansStoryDivision } from "./data/newTestament/philippians";
import { firstThessaloniansStoryDivision } from "./data/newTestament/1_thessalonians";
import { secondThessaloniansStoryDivision } from "./data/newTestament/2_thessalonians";
import { firstTimothyStoryDivision } from "./data/newTestament/1_timothy";
import { secondTimothyStoryDivision } from "./data/newTestament/2_timothy";
import { titusStoryDivision } from "./data/newTestament/titus";
import { philemonStoryDivision } from "./data/newTestament/philemon";
import { hebrewsStoryDivision } from "./data/newTestament/hebrews";
import { jamesStoryDivision } from "./data/newTestament/james";
import { firstPeterStoryDivision } from "./data/newTestament/1_peter";
import { secondPeterStoryDivision } from "./data/newTestament/2_peter";
import { firstJohnStoryDivision } from "./data/newTestament/1_john";
import { secondJohnStoryDivision } from "./data/newTestament/2_john";
import { thirdJohnStoryDivision } from "./data/newTestament/3_john";
import { judeStoryDivision } from "./data/newTestament/jude";
import { revelationStoryDivision } from "./data/newTestament/revelation";
import { seedLeaderboard } from "./scripts/insertLeaderboard";
import { insertWinner, seedWinners } from "./scripts/insertWinners";
import { colossiansStoryDivision } from "./data/newTestament/colossians";
async function run() {
  await login();

  // Old Testament
  // await insertBook(genesisBookContent);
  //  await insertBook(exodusStoryDivision);
  //await insertBook(leviticusStoryDivision);
  // await insertBook(numbersStoryDivision);
  // await insertBook(deuteronomyStoryDivision);
  await insertBook(joshuaStoryDivision);
  // await insertBook(judgesStoryDivision);
  // await insertBook(ruthStoryDivision);
  // await insertBook(firstSamuelStoryDivision);
  // await insertBook(secondSamuelStoryDivision);
  // await insertBook(firstKingsStoryDivision);
  // await insertBook(secondKingsStoryDivision);
  // await insertBook(firstChroniclesStoryDivision);
  // await insertBook(secondChroniclesStoryDivision);
  // await insertBook(ezraStoryDivision);
  // await insertBook(nehemiahStoryDivision);
  // await insertBook(estherStoryDivision);
  // await insertBook(jobStoryDivision);
  // await insertBook(psalmsBookContent);
  // await insertBook(proverbsStoryDivision);
  // await insertBook(ecclesiastesStoryDivision);
  // await insertBook(songOfSongsStoryDivision);
  // await insertBook(isaiahStoryDivision);
  // await insertBook(jeremiahStoryDivision);
  // await insertBook(lamentationsStoryDivision);
  // await insertBook(ezekielStoryDivision);
  // await insertBook(danielStoryDivision);
  // await insertBook(hoseaStoryDivision);
  // await insertBook(joelStoryDivision);
  // await insertBook(amosStoryDivision);
  // await insertBook(obadiahStoryDivision);
  // await insertBook(jonahStoryDivision);
  // await insertBook(micahStoryDivision);
  // await insertBook(nahumStoryDivision);
  // await insertBook(habakkukStoryDivision);
  // await insertBook(zephaniahStoryDivision);
  // await insertBook(haggaiStoryDivision);
  // await insertBook(zechariahStoryDivision);
  // await insertBook(malachiStoryDivision);

  // New Testament
  // await insertBook(matthewBookContent);
  // await insertBook(markStoryDivision);
  // await insertBook(lukeStoryDivision);
  // await insertBook(johnStoryDivision);
  // await insertBook(actsStoryDivision);
  // await insertBook(romansStoryDivision);
  // await insertBook(firstCorinthiansStoryDivision);
  //  await insertBook(secondCorinthiansStoryDivision);
  // await insertBook(galatiansStoryDivision);
  //await insertBook(ephesiansStoryDivision);
  // await insertBook(philippiansStoryDivision);
  // await insertBook(firstThessaloniansStoryDivision);
  //await insertBook(secondThessaloniansStoryDivision);
  //await insertBook(firstTimothyStoryDivision);
  //await insertBook(secondTimothyStoryDivision);
  //await insertBook(titusStoryDivision);
  //await insertBook(philemonStoryDivision);
  //await insertBook(hebrewsStoryDivision);
  //await insertBook(jamesStoryDivision);
  //await insertBook(firstPeterStoryDivision);
  //await insertBook(secondPeterStoryDivision);
  // await insertBook(firstJohnStoryDivision);
  // await insertBook(secondJohnStoryDivision);
  // await insertBook(thirdJohnStoryDivision);
  //await insertBook(judeStoryDivision);
  // await insertBook(revelationStoryDivision);
  // await insertBook(colossiansStoryDivision);
  //await seedLeaderboard();
  //await seedWinners();
}

run();

// npm run seed
